### PR TITLE
Force explicit int cast for decoct in PHP8

### PR DESCRIPTION
**Pull request by pjft**
In PHP8 at least, the lack of cast was causing large values to be read as strings, causing errors such as this one: https://github.com/owncloud/TarStreamer/issues/23#issuecomment-1449700060

In my case, this happened when a large file had to be added to the Tar archive. Forcing the (int) cast seems to have fixed it for me, and the files are downloaded correctly. I don't expect any issues with PHP7 either, but please review if it's acceptable or if there's any other area where this would fit best.

Thanks.

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by pjft** [comment]
Thank you!

**Comment by szaimen** [comment]
Hi @DeepDiver1975 can you please create a new release that contains this fix? Thank you in advance!

**Comment by DeepDiver1975** [comment]
@szaimen https://packagist.org/packages/owncloud/tarstreamer#v2.1.0

**Comment by szaimen** [comment]
A, havent seen that. Thanks a lot! :)

**Comment by DeepDiver1975** [comment]
> A, havent seen that. Thanks a lot! :)

just created a few minutes ago :smile:

**Pull request merged**
