### PR TITLE
Add long filenames support via L-header

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes https://github.com/owncloud/TarStreamer/issues/4

### CODE REVIEW

**Comment by VicDeo** [comment]
@DeepDiver1975

**Comment by DeepDiver1975** [comment]
Nice - THX

@LukasReschke mind testing the two options regarding file name length on mac? THX

**Comment by PVince81** [comment]
@tomneedham I heard you have a Mac ?

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by PVince81** [comment]
@VicDeo @DeepDiver1975 do we need to bump tarstreamer in core or wait for dependabot to find it ?

**Comment by DeepDiver1975** [comment]
dependabot shall do this - it is it's job to do so ... but we need to tag a version .... will take care

**Comment by DeepDiver1975** [comment]
https://packagist.org/packages/owncloud/tarstreamer#0.1.1

**Pull request merged**
