### PR TITLE
[0.2.0] Add PHP 7.3 to the matrix, drop PHP 5.4, 5.5, 5.6, 7.0

### PR DESCRIPTION
**Pull request by VicDeo**
Drop PHP 5.4, 5.5, 5.6, 7.0
Add PHP 7.3

### TODO
- [ ] review composer dependency versions
- [ ] bump required PHP version to 7.1

### CODE REVIEW

**Comment by phil-davis** [comment]
Could also drop PHP 5.6 and 7.0? That will save having to bother sorting out CI  for those.
The PHP 7.1 job is somehow trying to run phpunit v8, which is for PHP 7.2 upwards only.

**Comment by VicDeo** [comment]
@DeepDiver1975 what do you think on dropping PHP 7.0 support here?

**Comment by VicDeo** [comment]
@phil-davis my sense of beauty tells me that a bugfix release should be done before cutting the compatibility... 
From my standpoint we can drop 7.0 and below after the release incuding https://github.com/owncloud/TarStreamer/pull/11

**Comment by DeepDiver1975** [comment]
> From my standpoint we can drop 7.0 and below after the release incuding #11

let there first be a 0.1.2 which holds the fixes as per #11 and then we do a 0.2.0 with updated php dependencies

**Review by micbar — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
2.0.0 just got released - fyi ...

**Pull request merged**
